# Generated by Django 4.1.3 on 2022-11-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0003_message_priority_message_staff_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
